

name: Node.js CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*'
  pull_request:
    branches: [ "master" ]
    tags:
      - 'v*.*'

permissions:
  contents: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Check for CNAME file in build
      run: |
        if [ -f build/CNAME ]; then
          echo "CNAME file found in build directory:"
          cat build/CNAME
        else
          echo "No CNAME file found in build directory."
        fi

    - run: npm test


    - name: Deploy with gh-pages
      if: startsWith(github.ref, 'ref/tags/v1.') && github.event_name == 'push'
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
